# -*- coding: utf-8 -*-
"""Hospital Management System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1boYB2Q_ZtzdWeGS53-JKS-_k24yUDF_o
"""

# Updated Hospital Management System V2
# Coded by: The One, The Only... Camron Hylton (and yes I did all of this by myself, Thank you very much 😎)
# Let's manage some doctors and patients, for real

import uuid
from datetime import datetime

def load_banned_words():
  try:
    with open("banned_words.txt", "r", encoding="utf-8") as file:
      return [word.strip().lower() for word in file if word.strip()]
  except FileNotFoundError:
    print("⚠️ banned_words.txt file is missing!")
    return []

BANNED_WORDS = load_banned_words()

# 🚨 Check for any inappropriate words
def contains_banned_word(text):
  text_lower = text.lower()
  return any(bad_word in text_lower for bad_word in BANNED_WORDS)


# 🧠 Base user class for shared human stuff
class User:
    def __init__(self, name):
        self.name = name

# 🧍 Patient class (aka the ones who need help lol)
class Patient(User):
    def __init__(self, name, age, gender):
        super().__init__(name)
        self.patient_id = f"P-{uuid.uuid4().hex[:6]}"
        self.age = age
        self.gender = gender
        self.appointment_list = []

    def display_info(self):
        return f"Patient [{self.patient_id}]: {self.name}, Age: {self.age}, Gender: {self.gender}"

# 👨‍⚕️ Doctor class (the real MVPs)
class Doctor(User):
    def __init__(self, name, specialty, available_slots):
        super().__init__(name)
        self.doctor_id = f"D-{uuid.uuid4().hex[:5]}"
        self.specialty = specialty
        self.available_slots = set(available_slots)

    def is_available(self, slot):
        return slot in self.available_slots

    def view_schedule(self):
        return sorted(self.available_slots)

    def book_slot(self, slot):
        self.available_slots.discard(slot)

# 📅 Appointment class - where the magic happens
class Appointment:
    def __init__(self, patient, doctor, date, time):
        self.appointment_id = f"A-{uuid.uuid4().hex[:6]}"
        self.patient = patient
        self.doctor = doctor
        self.date = date
        self.time = time
        self.status = "Scheduled"

    def confirm(self):
        self.status = "Confirmed"

    def cancel(self):
        self.status = "Cancelled"

    def display(self):
        return (
            f"Appointment {self.appointment_id}: {self.patient.name} with Dr. {self.doctor.name} "
            f"on {self.date} at {self.time} | Status: {self.status}"
       )


# 💸 Billing class - cuz nothing's free 😬
class Billing:
    def __init__(self, appointment, extra_services=None):
        self.appointment_list = appointment
        self.base_fee = 300
        self.extra_services = extra_services or []

    def total(self):
        return self.base_fee + sum(self.extra_services)

    def print_receipt(self):
        print("\\n--- Billing Receipt ---")
        print(f"Appointment ID: {self.appointment.appointment_id}")
        print(f"Patient: {self.appointment.patient.name}")
        print(f"Doctor: {self.appointment.doctor.name}")
        print(f"Base Fee: ${self.base_fee}")
        print(f"Extras: ${sum(self.extra_services)}")
        print(f"Total: ${self.total()} 💸")
        print("-----------------------\\n")

# 🏥 Main hospital system logic - the mothership
class HospitalSystem:
    def __init__(self):
        self.patients = {}
        self.doctors = {}
        self.appointments_list = {}

    def add_patient(self, name, age, gender):
        # sanity check, this ain't the old folks home 🧓
        if age >= 100 or age <= 0:
            print("Invalid age. That number doesn't exist, you crazy! 😭")
            return
        if gender.lower() not in ["male", "female"]:
            print("Please enter 'Male or Female' for gender")
            return

        p = Patient(name, age, gender)
        self.patients[p.patient_id] = p
        print(f"Patient registered with ID: {p.patient_id} ✅")

    def add_doctor(self, name, specialty, slots):
        # Doc just clocked in ⏰
        d = Doctor(name, specialty, slots)
        self.doctors[d.doctor_id] = d
        print(f"Doctor added with ID: {d.doctor_id} 🩺")

    def book_appointment(self, pid, did, slot):
        print("Trying to book that appointment... fingers crossed 🤞")
        patient = self.patients.get(pid)
        doctor = self.doctors.get(did)
        if not patient or not doctor:
            print("Invalid patient or doctor ID. Bro, check your inputs 💀")
            return

        if not doctor.is_available(slot):
            print("Doc is booked at that time 😤 Choose another slot.")
            return

        # Secure the bag 🔒
        appointment = Appointment(patient, doctor, slot)
        doctor.book_slot(slot)
        patient.appointments.append(appointment)
        self.appointments_list[appointment.appointment_id] = appointment
        print(f"Appointment confirmed! ID: {appointment.appointment_id} 🎉")

    def cancel_appointment(self, aid):
        appt = self.appointments_list.get(aid)
        if appt:
            appt.cancel()
            print("Appointment cancelled. RIP 🪦")
        else:
            print("Appointment not found. That ID's ghosting us 👻")

    def generate_bill(self, aid):
        appt = self.appointments_list.get(aid)
        if not appt:
            print("Appointment ID not found. You sure that's real? 🤨")
            return

        extras = input("Drop extra charges (comma separated): ")
        extra_costs = list(map(int, extras.split(','))) if extras else []
        bill = Billing(appt, extra_costs)
        bill.print_receipt()

# 🕹️ CLI time - where user meets code
def start_cli():
    system = HospitalSystem()

    while True:
        print("\n")
        print("╔═══════════════════════════════════════╗")
        print("║           VITALCARE HOSPITAL          ║")
        print("║      'Your Health, Our Priority'      ║")
        print("╚═══════════════════════════════════════╝")

        print("✨ Welcome to VitalCare Hospital System ✨\n")
        print("=====~ M        E        N        U ~=====\n")
        print("How can I help you today?\n")
        print("1. Add Patient 🧍")
        print("2. Add Doctor 👨‍⚕️")
        print("3. Book Appointment 📅")
        print("4. Exit 🚪")

        choice = input("Pick your vibe (1-4): ")
        print("------------------------------------------------------- \n")

        match choice:
            case "1":
              try:
                name = input("Patient Name: ")
                if len(name.split()) < 2 or not name.replace(" ", "").isalpha():
                  raise ValueError("⚠️ Sir/Madam, please use your full name (first and last), letters only. No numbers or symbols.")

                if contains_banned_word(name):
                  raise ValueError("Whoa, that name's not appropriate for this system. Try again respectfully.")

                age = int(input("Age: "))
                if age > 100 or age <= 0:
                  raise ValueError("That number doesn't exist! Try again.")

                gender = input("Gender (Male/Female): ").strip().capitalize()
                if gender not in ["Male", "Female"]:
                  raise ValueError("🚷 Use your appropriate genders, please. And that way we will understand")

                system.add_patient(name, age, gender)

              except ValueError as ve:
                print(ve)
                return

            case "2":
              try:
                name = input("Doctor Name: ")
                if len(name.split()) < 2 or not name.replace(" ", "").isalpha():
                   raise ValueError("👨‍⚕️ Please enter the doctor's full name (first and last), letters only.")
                if contains_banned_word(name):
                   raise ValueError("💢 That's not an acceptable name. Be respectful.")

                print("\n--- Choose your Specialty---\n")
                print("1. Doctor")
                print("2. Nurse")
                print("3. Cardiologist")
                print("4. Dermatologist")
                print("5. Pediacritran")
                print("6. Radiologist")
                print("7. Suregon")
                print("8. Psychiatrist")
                print("9. Neurologist")
                print("10. Oncologist")
                print("11. Orthopedic")
                print("12. Gynecologist \n")

                spec_choice= input("Enter the number for the specialty: ").strip()
                spec_map= {
                       "1": "Doctor",           # ⚕️ Promote, maintain & restore health
                       "2": "Nurse",            # ⚕️ Provide compassionate, care for patients in all ages.
                       "3": "Cardiologist",     # ❤️ Heart doctor
                       "4": "Dermatologist",    # 🧴 Skin doctor
                       "5": "Pediatrician",     # 👶 Children's doctor
                       "6": "Surgeon",          # 🔪 Performs surgeries to patients
                       "7": "Psychiatrist",     # 🧠 Mental health doctor
                       "8": "Neurologist",      # 🧠 Brains & nerves
                       "9": "Orthopedic",       # 🦴 Bones & joints specialist
                      "10": "Gynecologist",     # 👩 Women's Health
                  }

                if spec_choice not in spec_map:
                    print("⚠️ Invaild specialty selction. Try again next time")
                    break

                specialty = spec_map[spec_choice]

                slots = input("Available Slots (comma-separated e.g. '2025-07-01 10:00'): ").split(",")
                system.add_doctor(name, specialty, [s.strip() for s in slots])

              except ValueError as ve:
                print(ve)

            case "3":
                pid = input("Patient ID: ")
                did = input("Doctor ID: ")
                slot = input("Slot (e.g. 2025-07-01 10:00): ")
                system.book_appointment(pid, did, slot)

            case "4":
                confirm1 = input("Are you sure you want to exit? (yes/no): ").lower()
                if confirm1 == "yes":
                    confirm2 = input("Are you 100% SURE you want to exit the system? 🤔 (yes/no): ").lower()
                    if confirm2 == "yes":
                      confirm3 = input("Remember there's no going back... are you postive? 😳 (yes/no): ").lower()
                      if confirm3 == "yes":

                        print("Alrighty then, logging off... Stay hydrated ✌️")
                        break
                    else:
                        print("Changed your mind? Smart move 🧠")
                else:
                    print("Back to business then 💼")
            case _:
                print("Nah that ain't a valid choice. Try again 🤖")


# Main menu that directs users to either registration or login
def main_menu():
  while True:
    print("\n1. New User (Resgister as Patient or Doctor)")
    print("2. Returning User (Login to Portal)\n")

    main_choice = input("Choose you path (1-2): ")

    match main_choice:
      case "1":
        start_cli()
      case "2":
        login_menu()
      case _:
        print("⚠️ Invaild choice. Try again.")

def login_menu():
  system = ()
  while True:
    print("\nReturning User Portal\n")
    print("1.🧍 Patient Login")
    print("2.👨‍⚕️ Doctor Login")
    print("3.❌ Cancel Appointment")
    print("4.💸 Generate Bill")
    print("5. Exit")

    login_choice = input("Who are you? (1-5): ")

    match login_choice:
       case "1":
        patient_id = input("Enter your Patient ID: ")
        if patient_id in system.patients:
          print("Welcome back!", system.patients[patient_id]['name'])
          def patient_actions(system, patient_id):
           pass
        else:
          print("❌ Invaild Patient ID. Try again.")

       case "2":
        doctor_id = input("Enter your Doctor ID: ")
        if doctor_id in system.doctors:
          print("✅ Doctor logged in successfully.")
          def doctor_actions(system, doctor_id):
           pass
        else:
          print("❌ Invaild Doctor ID. Try again")

          patient_actions(system, doctor_id)
          doctor_actions(system, doctor_id)

       case "3":
        aid = input("Appointment ID: ")
        system.cancel_appointment(aid)

       case "4":
        aid = input("Appointment ID for Billing: ")
        system.generate_bill(aid)

       case "5":
        print("✌️ Goodbye. See you again!")
        break

       case _:
          print("⚠️ Invaild option.Try again")

# 🎬 Run the drama
if __name__ == "__main__":
    main_menu()

if __name__ == "__main__":
    start_cli()